version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 10
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
       
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - 5601:5601  
    networks:
      - esnet      
    depends_on:
      elasticsearch:
        condition: service_healthy      
       
 
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
 
networks:
  esnet: